### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ricardograca** [webBoxio/atom-color#10]
I just installed this package and it doesn't work. No errors on the developer console, except deprecation warnings. Changing the only available setting does nothing. Enabling or disabling "Show Invisibles" also doesn't help. Restart Atom also does nothing.

Ubuntu 14.04, Atom 0.175.0.

**Comment by kevin39** [comment]
Same here since I updated to the last Atom release (0.176) and updated all my packages.

**Comment by vigo** [comment]
Unfortunately, author of this package is not around... I'm not able fix issues. Due to deprecations, there some lines to fix. We need help :)

**Comment by kevin39** [comment]
I think this is the reason : https://atom.io/docs/latest/upgrading/upgrading-your-package
But I don't have enough time to upgrade this package. I don't know the Atom API. Hope the author will be back ;)

**Comment by gmoore-sjcorg** [comment]
I went ahead and hacked on this a bit and submitted a pull request. Probably not the cleanest but its working. https://github.com/gmoore-sjcorg/atom-color
