### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by krueschi** [webBoxio/atom-color#22]
Hi,
got the following message (as a yellow exclamation mark in the status line of atom):

Store package style sheets in the  `styles/`  directory instead of  `stylesheets/`  in the  webbox-color  package

Package.getStylesheetsPath  [path-to-atom]\app-0.190.0\resources\app\src\package.js:433:9  Package.getStylesheetPaths  [path-to-atom]\app-0.190.0\resources\app\src\package.js:433:32     

(notice: Windows version)

**Comment by yavoo** [comment]
The same on mac os version

**Comment by JacobEvelyn** [comment]
+1
