### ISSUE TITLE
Error: Cannot find module 'underscore-plus'

### ISSUE THREAD

**Issue by nemoDreamer** [webBoxio/atom-color#3]
Console shows:
Failed to activate package named 'atom-color'
Error: Cannot find module 'underscore-plus'

(Might be a side-effect of not taking advantage of Atom's dependency management due to https://github.com/webBoxio/atom-color/issues/2 ?)

**Comment by vigo** [comment]
#2 fixed, can you please re-try?

**Comment by nemoDreamer** [comment]
Works!
