### ISSUE TITLE
Hex Colors under Windows

### ISSUE THREAD

**Issue by mastastealth** [webBoxio/atom-color#4]
Hex (long or short) color support doesn't seem to working under Atom (Windows, SCSS file, React is enabled)

**Comment by vigo** [comment]
Hi, can you please update and re-try? sass support just added. Please report if it is not working still... ok?

**Comment by mastastealth** [comment]
Yup! Everything seems to be working fine in the current builds.

**Comment by vigo** [comment]
ok kool!
