### ISSUE TITLE
Deprecated selector in `webbox-color\styles\color.less`

### ISSUE THREAD

**Issue by everuniverse** [webBoxio/atom-color#45]
In `webbox-color\styles\color.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .color-box.on-background,
atom-text-editor::shadow .color-box.on-background` => `atom-text-editor .color-box.on-background,
atom-text-editor.editor .color-box.syntax--on-background`

* `atom-text-editor .color-box.on-line-end,
atom-text-editor::shadow .color-box.on-line-end` => `atom-text-editor .color-box.on-line-end,
atom-text-editor.editor .color-box.on-line-end`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by GingerN** [comment]
Same, plugin is not working

**Comment by Khovanov** [comment]
Same

**Comment by ninoM** [comment]
Same..

**Comment by GMGrimley** [comment]
+1

**Comment by PavelEfimenko** [comment]
+

**Comment by HugoGon** [comment]
+1

**Comment by garrettw** [comment]
@everuniverse why did you close this? It hasn't been fixed.

**Comment by everuniverse** [comment]
@garrettw same issue has been reported before. (#44 is still open)

**Comment by pedrosmmc** [comment]
Closed?! This is a very useful package with no other alternative so far and if is so easy to fix it why not corret it?

**Comment by lolxy** [comment]
+1
